name: Refresh video

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: Video id or video url
        required: true
        type: string

jobs:
  refresh-video:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: tsc --build
      - run: npm run refreshVideo
        env:
          VIDEO_ID: ${{ inputs.videoId }}
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git commit -m "RV `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
      - run: git push || echo "Nothing to push"
