name: Retry data retrieval

on:
  workflow_dispatch:
  schedule:
    - cron: '43 9 * * *'

concurrency: modifying-action

jobs:
  refresh-video:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run retryDataRetrieval
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git commit -m "RDR `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
      - run: git push || echo "Nothing to push"
